// integration/angular/projects/effects/src/app/theme/theme.component.ts
import { Component } from '@angular/core';
import { Apollo } from '@apollo-orbit/angular';
import { ThemeName, ThemeQuery } from '../graphql';
import { ToggleThemeAction } from '../states/theme/theme.actions';

@Component({
  selector: 'app-theme',
  templateUrl: './theme.component.html',
  styleUrls: ['./theme.component.scss']
})
export class ThemeComponent {
  public readonly themeName = ThemeName;
  public readonly themeQuery = this.apollo.cache.watchQuery(new ThemeQuery());

  public constructor(
    private readonly apollo: Apollo
  ) { }

  public toggleTheme(): void {
    this.apollo.dispatch(new ToggleThemeAction());
  }
}

@if (themeQuery | async; as themeData) {
<div class="container">
  <span>Current theme:</span>
  <b>{{ themeData.theme.displayName }}</b>
  <button type="button" (click)="toggleTheme()">Toggle theme</button>
</div>
}

// integration/react/src/Theme.tsx
import { useDispatch, useQuery } from '@apollo-orbit/react';
import { ThemeDocument } from './graphql';
import { ToggleThemeAction } from './states/theme/theme.actions';

export function Theme() {
  const dispatch = useDispatch();
  const { data: themeData } = useQuery(ThemeDocument);

  return (
    <div>
      <span>Current theme:</span>
      &nbsp;
      <b>{themeData?.theme.displayName}</b>
      &nbsp;
      <button onClick={() => dispatch<ToggleThemeAction>({ type: 'theme/toggle' })}>Toggle theme</button>
    </div>
  );
}
