// integration/react/src/library/Library.tsx
import React, { Suspense, useState } from 'react';
import { Authors } from './Authors';
import { Books } from './Books';
import './Library.scss';
import { NewAuthor } from './NewAuthor';
import { NewBook } from './NewBook';

const Lazy = React.lazy(() => import('../lazy/Lazy'));

export function Library() {
    const [isAddingBook, setIsAddingBook] = useState(false);
    const [isAddingAuthor, setIsAddingAuthor] = useState(false);
    const [showLazy, setShowLazy] = useState(false);

    return (
        <>
            <Books></Books>
            <Authors></Authors>
            <br />
            <button onClick={() => setIsAddingBook(true)}>Add Book</button>
            &nbsp;
            <button onClick={() => setIsAddingAuthor(true)}>Add Author</button>
            {isAddingBook && <div className="form-container" style={{ marginTop: '5px' }}>
                <NewBook onClose={() => setIsAddingBook(false)}></NewBook>
            </div>}
            {isAddingAuthor && <div className="form-container" style={{ marginTop: '5px' }}>
                <NewAuthor onClose={() => setIsAddingAuthor(false)}></NewAuthor>
            </div>}
            <br />
            <br />
            {!showLazy && <button onClick={() => setShowLazy(true)}>Go to lazy</button>}
            {showLazy && <button onClick={() => setShowLazy(false)}>Go back</button>}
            {showLazy && <div>
                <Suspense fallback={<div>Loading...</div>}>
                    <Lazy />
                </Suspense>
            </div>}
        </>
    );
}

// integration/angular/projects/state/src/app/library/library.component.ts
import { Component, signal } from '@angular/core';
import { AuthorsComponent } from './authors/authors.component';
import { BooksComponent } from './books/books.component';
import { NewAuthorComponent } from './new-author/new-author.component';
import { NewBookComponent } from './new-book/new-book.component';

@Component({
  selector: 'app-library',
  templateUrl: './library.component.html',
  styleUrls: ['./library.component.scss'],
  imports: [BooksComponent, NewBookComponent, NewAuthorComponent, AuthorsComponent]
})
export class LibraryComponent {
  protected isAddingBook = signal(false);
  protected isAddingAuthor = signal(false);

  protected addBook(): void {
    this.isAddingBook.set(true);
  }

  protected cancelAddBook(): void {
    this.isAddingBook.set(false);
  }

  protected addAuthor(): void {
    this.isAddingAuthor.set(true);
  }

  protected cancelAddAuthor(): void {
    this.isAddingAuthor.set(false);
  }
}

<app-books></app-books>
<app-authors></app-authors>
<br />
<div class="actions-container">
  <button type="button" (click)="addBook()">Add Book</button>
  <button type="button" (click)="addAuthor()">Add Author</button>
</div>
@if (isAddingBook()) {
<app-new-book (onClose)="cancelAddBook()"></app-new-book>
}
@if (isAddingAuthor()) {
<app-new-author (onClose)="cancelAddAuthor()"></app-new-author>
}
