// integration/react/src/library/NewBook.tsx
import { useLazyQuery, useMutation } from '@apollo/client/react';
import { FormEvent, useState } from 'react';
import { ADD_BOOK_MUTATION, AUTHORS_QUERY } from '../graphql';

export function NewBook({
  onClose
}: {
  onClose: () => void;
}) {
  const [addBook, { loading: submitting }] = useMutation(ADD_BOOK_MUTATION);
  const [getAuthors, authorsResult] = useLazyQuery(AUTHORS_QUERY, {
    notifyOnNetworkStatusChange: true,
    fetchPolicy: 'no-cache'
  });
  const [name, setName] = useState<string | undefined>();
  const [genre, setGenre] = useState<string | undefined>();
  const [selectedAuthorId, setSelectedAuthorId] = useState<string | undefined>();
  const authorId = selectedAuthorId ?? authorsResult.data?.authors[0]?.id;

  const handleSubmit = (evt: FormEvent) => {
    evt.preventDefault();
    if (!name || !authorId) return;
    addBook({
      variables: {
        book: { authorId, name, genre }
      }
    });
  };

  return (
    <>
      {submitting && <div>Submitting...</div>}
      <form onSubmit={handleSubmit} className="box">
        <div>
          <label>Name:&nbsp;</label>
          <input type="text" onChange={event => setName(event.target.value)} />
        </div>
        <div>
          <label>Genre:&nbsp;</label>
          <input type="text" onChange={event => setGenre(event.target.value)} />
        </div>

        {!authorsResult.called
          ? <div><button type="button" onClick={() => getAuthors()}>Load authors</button></div>
          : <>
            {authorsResult.loading && <div>Loading authors...</div>}
            {authorsResult.error && <div>{authorsResult.error.message}</div>}
            {authorsResult.data && <div>
              <label>Author:&nbsp;</label>
              <select onChange={event => setSelectedAuthorId(event.target.value)}>
                {authorsResult.data.authors.map(author => <option key={author.id} value={author.id}>{author.name}</option>)}
              </select>
            </div>}
          </>}
        <br />
        <button disabled={!name || !authorId}>Submit</button>
        <button type="button" onClick={() => onClose()}>Close</button>
      </form>
    </>
  );
}

// integration/angular/projects/core/src/app/library/new-book/new-book.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, Output, signal } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { Apollo } from '@apollo-orbit/angular/core';
import { cache } from 'decorator-cache-getter';
import { AddBookMutation, AuthorsQuery, BookInput } from '../../graphql';

@Component({
  selector: 'app-new-book',
  templateUrl: './new-book.component.html',
  styleUrls: ['./new-book.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class NewBookComponent {
  @Output() public readonly onClose = new EventEmitter<void>();

  public readonly authorsQuery = this.apollo.watchQuery({ ...new AuthorsQuery(), fetchPolicy: 'cache-and-network' });
  public readonly error = signal<Error | undefined>(undefined);

  public constructor(
    private readonly apollo: Apollo,
    private readonly fb: FormBuilder
  ) { }

  @cache
  public get form() {
    return this.fb.group({
      name: this.fb.control<string | null>(null, Validators.required),
      genre: this.fb.control<string | null>(null),
      authorId: this.fb.control<string | null>(null, Validators.required)
    });
  }

  public submit(): void {
    if (!this.form.valid) return;
    const book = this.form.value as BookInput;
    this.error.set(undefined);
    this.apollo.mutate(new AddBookMutation({ book })).subscribe({
      error: (error: Error) => this.error.set(error)
    });
  }
}

@if (authorsQuery | async; as authorsResult) {
@if (authorsResult.loading) { Loading... }
@if (authorsResult.error) { {{ authorsResult.error.message }} }
@if (authorsResult.data?.authors; as authors) {
<form [formGroup]="form" autocomplete="off" (ngSubmit)="submit()">
  @if (error(); as error) {
  <div class="error-well">An error has occurred: {{ error.message }}</div>
  }
  <div class="form-group">
    <label for="name">Name *</label>
    <input name="name" type="text" formControlName="name" />
  </div>
  <div class="form-group">
    <label for="genre">Genre</label>
    <input name="genre" type="text" formControlName="genre" />
  </div>
  <div class="form-group">
    <label for="author">Author *</label>
    <select name="author" formControlName="authorId">
      @for (author of authors; track author) {
      <option [value]="author.id">{{ author.name }}
      </option>
      }
    </select>
  </div>
  <div class="form-buttons">
    <button type="submit">Submit</button>
    <button type="button" (click)="onClose.next()">Close</button>
  </div>
</form>
}
}
