// integration/react/src/library/Books.tsx
import { useQuery } from '@apollo/client/react';
import { BOOKS_QUERY } from '../graphql';

export function Books() {
  const { refetch, ...booksResult } = useQuery(BOOKS_QUERY, { notifyOnNetworkStatusChange: true });

  return (
    <>
      <h3>Books <button className="link" onClick={() => refetch()}>⟳</button></h3>
      {booksResult.loading && <div>Loading...</div>}
      {booksResult.error && <div className="error-well">{booksResult.error.message}</div>}
      {(booksResult.data ?? booksResult.previousData)?.books.map(book =>
        <div key={book.id}>
          <span>{book.displayName}</span>
        </div >
      )}
    </>
  );
}

// integration/angular/projects/effects/src/app/library/books/books.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Apollo } from '@apollo-orbit/angular';
import { BooksQuery } from '../../graphql';

@Component({
  selector: 'app-books',
  templateUrl: './books.component.html',
  styleUrls: ['./books.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class BooksComponent {
  public readonly booksQuery = this.apollo.watchQuery({ ...new BooksQuery(), notifyOnNetworkStatusChange: true });

  public constructor(
    private readonly apollo: Apollo
  ) { }

  public refetch(): void {
    this.booksQuery.refetch();
  }
}

<h3>Books <a href="javascript: void 0" (click)="refetch()">⟳</a></h3>
<ng-container *ngIf="booksQuery | async as booksResult">
  <ng-container *ngIf="booksResult.loading">Loading...</ng-container>
  <ng-container *ngIf="booksResult.error">{{ booksResult.error.message }}</ng-container>
  <ng-container *ngIf="(booksResult.data || booksResult.previousData)?.books  as books">
    <div *ngFor="let book of books">
      <span>{{ book.displayName }}</span>
    </div>
  </ng-container>
</ng-container>
