// integration/react/src/library/Authors.tsx
import { useQuery, useSubscription } from '@apollo/client/react';
import { AUTHORS_QUERY, NEW_AUTHOR_SUBSCRIPTION } from '../graphql';

export function Authors() {
  const { refetch, ...authorsResult } = useQuery(AUTHORS_QUERY);
  const { data: newAuthorData } = useSubscription(NEW_AUTHOR_SUBSCRIPTION);

  return (
    <>
      <h3>Authors <button className="link" onClick={() => refetch()}>⟳</button></h3>
      {newAuthorData && <div className="notification">New author added: <b>{newAuthorData.newAuthor.name}</b></div>}
      {authorsResult.loading && <div>Loading...</div>}
      {authorsResult.error && <div className="error-well">{authorsResult.error.message}</div>}
      {(authorsResult.data ?? authorsResult.previousData)?.authors.map(author =>
        <div key={author.id}>
          <span>{author.name}</span>
          <ul>
            {author.books.map(book => <li key={book.id}>{book.name}</li>)}
          </ul>
        </div >
      )}
    </>
  );
}

// integration/angular/projects/effects/src/app/library/authors/authors.component.ts
import { Component } from '@angular/core';
import { Apollo } from '@apollo-orbit/angular';
import { AuthorsQuery } from '../../graphql';

@Component({
  selector: 'app-authors',
  templateUrl: './authors.component.html',
  styleUrls: ['./authors.component.scss']
})
export class AuthorsComponent {
  public readonly authorsQuery = this.apollo.watchQuery({ ...new AuthorsQuery(), notifyOnNetworkStatusChange: true });

  public constructor(
    private readonly apollo: Apollo
  ) { }

  public refetch(): void {
    this.authorsQuery.refetch();
  }
}

<h3>Authors <a href="javascript: void 0" (click)="refetch()">⟳</a></h3>
<ng-container *ngIf="authorsQuery | async as authorsResult">
    <ng-container *ngIf="authorsResult.loading">Loading...</ng-container>
    <ng-container *ngIf="authorsResult.error">{{ authorsResult.error.message }}</ng-container>
    <ng-container *ngIf="(authorsResult.data || authorsResult.previousData)?.authors  as authors">
        <div *ngFor="let author of authors">
            <span>{{ author.name }}</span>
            <ul>
                <li *ngFor="let book of author.books">{{ book.name }}</li>
            </ul>
        </div>
    </ng-container>
</ng-container>
