// integration/angular/projects/effects/src/app/library/library.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-library',
  templateUrl: './library.component.html',
  styleUrls: ['./library.component.scss']
})
export class LibraryComponent {
  public isAddingBook = false;
  public isAddingAuthor = false;

  public addBook(): void {
    this.isAddingBook = true;
  }

  public cancelAddBook(): void {
    this.isAddingBook = false;
  }

  public addAuthor(): void {
    this.isAddingAuthor = true;
  }

  public cancelAddAuthor(): void {
    this.isAddingAuthor = false;
  }
}

<app-books></app-books>
<app-authors></app-authors>
<br />

<div class="actions-container">
    <button (click)="addBook()">Add Book</button>
    <button (click)="addAuthor()">Add Author</button>
</div>

<div *ngIf="isAddingBook" class="form-container">
    <app-new-book (onClose)="cancelAddBook()"></app-new-book>
</div>

<div *ngIf="isAddingAuthor" class="form-container">
    <app-new-author (onClose)="cancelAddAuthor()">
    </app-new-author>
</div>

// integration/react/src/library/Library.tsx
import React, { Suspense, useState } from 'react';
import { Authors } from './Authors';
import { Books } from './Books';
import './Library.scss';
import { NewAuthor } from './NewAuthor';
import { NewBook } from './NewBook';

const Lazy = React.lazy(() => import('../lazy/Lazy'));

export function Library() {
    const [isAddingBook, setIsAddingBook] = useState(false);
    const [isAddingAuthor, setIsAddingAuthor] = useState(false);
    const [showLazy, setShowLazy] = useState(false);

    return (
        <>
            <Books></Books>
            <Authors></Authors>
            <br />
            <button onClick={() => setIsAddingBook(true)}>Add Book</button>
            &nbsp;
            <button onClick={() => setIsAddingAuthor(true)}>Add Author</button>
            {isAddingBook && <div className="form-container" style={{ marginTop: '5px' }}>
                <NewBook onClose={() => setIsAddingBook(false)}></NewBook>
            </div>}
            {isAddingAuthor && <div className="form-container" style={{ marginTop: '5px' }}>
                <NewAuthor onClose={() => setIsAddingAuthor(false)}></NewAuthor>
            </div>}
            <br />
            <br />
            {!showLazy && <button onClick={() => setShowLazy(true)}>Go to lazy</button>}
            {showLazy && <button onClick={() => setShowLazy(false)}>Go back</button>}
            {showLazy && <div>
                <Suspense fallback={<div>Loading...</div>}>
                    <Lazy />
                </Suspense>
            </div>}
        </>
    );
}
