// integration/angular/projects/state/src/app/library/new-book/new-book.component.ts
import { ChangeDetectionStrategy, Component, EventEmitter, inject, Output } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Apollo } from '@apollo-orbit/angular';
import { cache } from 'decorator-cache-getter';
import { ADD_BOOK_MUTATION, gqlAuthorsQuery } from '../../graphql';

@Component({
  selector: 'app-new-book',
  templateUrl: './new-book.component.html',
  styleUrls: ['./new-book.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ReactiveFormsModule]
})
export class NewBookComponent {
  private readonly apollo = inject(Apollo);
  private readonly fb = inject(FormBuilder);

  @Output() public readonly onClose = new EventEmitter<void>();

  protected readonly authorsQuery = this.apollo.signal.query({ ...gqlAuthorsQuery(), lazy: true, fetchPolicy: 'no-cache' });
  protected readonly addBookMutation = this.apollo.signal.mutation(ADD_BOOK_MUTATION);

  @cache
  protected get form() {
    return this.fb.group({
      name: this.fb.nonNullable.control<string>('', Validators.required),
      genre: this.fb.control<string | null>(null),
      authorId: this.fb.nonNullable.control<string>('', Validators.required)
    });
  }

  protected submit(): void {
    if (!this.form.valid) return;
    const book = this.form.getRawValue();
    this.addBookMutation.mutate({ variables: { book } });
  }
}

<form class="form" [formGroup]="form" autocomplete="off" (ngSubmit)="submit()">
  @if (addBookMutation.error(); as error) {
  <div class="error-well">An error has occurred: {{ error.message }}</div>
  }
  <div class="form-field">
    <label for="name">Name *</label>
    <input name="name" type="text" formControlName="name" />
  </div>
  <div class="form-field">
    <label for="genre">Genre</label>
    <input name="genre" type="text" formControlName="genre" />
  </div>
  @if (!authorsQuery.active()) {
  <button type="button" (click)="authorsQuery.execute()">Load authors</button>
  } @else {
  @if (authorsQuery.loading()) { Loading... }
  @if (authorsQuery.error(); as error) { <div class="error-well">{{ error.message }}</div> }
  @if (authorsQuery.data()?.authors; as authors) {
  <div class="form-field">
    <label for="author">Author *</label>
    <select name="author" formControlName="authorId">
      @for (author of authors; track author) {
      <option [value]="author.id">{{ author.name }}
      </option>
      }
    </select>
  </div>
  }
  }
  <div class="form-buttons">
    <button type="submit" [disabled]="addBookMutation.loading()">Submit</button>
    <button type="button" (click)="onClose.next()">Close</button>
  </div>
</form>

// integration/react/src/library/NewBook.tsx
import { useLazyQuery, useMutation } from '@apollo/client/react';
import { FormEvent, useState } from 'react';
import { ADD_BOOK_MUTATION, AUTHORS_QUERY } from '../graphql';

export function NewBook({
  onClose
}: {
  onClose: () => void;
}) {
  const [addBook, { loading: submitting }] = useMutation(ADD_BOOK_MUTATION);
  const [getAuthors, authorsResult] = useLazyQuery(AUTHORS_QUERY, {
    notifyOnNetworkStatusChange: true,
    fetchPolicy: 'no-cache'
  });
  const [name, setName] = useState<string | undefined>();
  const [genre, setGenre] = useState<string | undefined>();
  const [selectedAuthorId, setSelectedAuthorId] = useState<string | undefined>();
  const authorId = selectedAuthorId ?? authorsResult.data?.authors[0]?.id;

  const handleSubmit = (evt: FormEvent) => {
    evt.preventDefault();
    if (!name || !authorId) return;
    addBook({
      variables: {
        book: { authorId, name, genre }
      }
    });
  };

  return (
    <>
      {submitting && <div>Submitting...</div>}
      <form onSubmit={handleSubmit} className="box">
        <div>
          <label>Name:&nbsp;</label>
          <input type="text" onChange={event => setName(event.target.value)} />
        </div>
        <div>
          <label>Genre:&nbsp;</label>
          <input type="text" onChange={event => setGenre(event.target.value)} />
        </div>

        {!authorsResult.called
          ? <div><button type="button" onClick={() => getAuthors()}>Load authors</button></div>
          : <>
            {authorsResult.loading && <div>Loading authors...</div>}
            {authorsResult.error && <div>{authorsResult.error.message}</div>}
            {authorsResult.data && <div>
              <label>Author:&nbsp;</label>
              <select onChange={event => setSelectedAuthorId(event.target.value)}>
                {authorsResult.data.authors.map(author => <option key={author.id} value={author.id}>{author.name}</option>)}
              </select>
            </div>}
          </>}
        <br />
        <button disabled={!name || !authorId}>Submit</button>
        <button type="button" onClick={() => onClose()}>Close</button>
      </form>
    </>
  );
}
